apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-auth
  labels:
    app: url-shortener-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener-auth
  template:
    metadata:
      labels:
        app: url-shortener-auth
    spec:
      containers:
      - name: url-shortener-auth
        image: junjiekoh/url-shortener-auth:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
        - name: POSTGRES_K8s_HOST
          value: "host.docker.internal"